TEXT_GAMEOVER  = "I'M SORRY, NO MORE CREDITS TO PLAY";
TEXT_PLAY      = "PLAY";
TEXT_CREDITS   = "CREDITS";
TEXT_SPIN      = "SPIN";
TEXT_PLUS      = "+";
TEXT_MIN       = "-";
TEXT_CURRENCY  = "$";
 
TEXT_HELP1     = 'CLICK ON "+" or "-" BUTTONS TO SELECT YOUR BET. PRIZE WILL VARY ACCORDING TO THE WAGER. THE MORE YOU BET, THE MORE YOU CAN WIN. WHEN YOU ARE READY, SPIN THE WHEEL TO PLAY!';
TEXT_HELP2     = "WHEN THE WHEEL STOPS SPINNING, YOU'LL BE SHOWN YOUR PRIZE!";